  name: Deploy Application
  on:
    push:
      branches:
        - develop

  jobs:
    create-deployment-artifacts:
      name: Create deployment artifacts
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Compile CSS and Javascript
          run: |
            npm install
            npm run prod

