  name: Deploy Application
  on:
    push:
      branches:
        - develop

  jobs:
    create-deployment-artifacts:
      name: Create deployment artifacts
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Compile CSS and Javascript
          run: |
            npm i
            npm run build

        - name: Configure php 8.2
          uses: shivammathur/setup-php@master
          with:
            php-version: 8.2
            extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

